apiVersion: v1
kind: Secret
metadata:
  name: store-secrets
  namespace: {{ .Release.Namespace }}
stringData:
  mysql-root-password: {{ .Values.mysql.rootPassword | quote }}
  mysql-password: {{ .Values.mysql.password | quote }}
  wordpress-password: {{ .Values.wordpress.adminPassword | quote }}
  wordpress-email: {{ .Values.wordpress.adminEmail | quote }}
