apiVersion: v1
kind: Service
metadata:
  name: urumi-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: urumi-platform-api
spec:
  type: {{ .Values.platform.api.service.type }}
  ports:
    - port: {{ .Values.platform.api.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: urumi-platform-api
