apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: {{ .Release.Namespace }}
stringData:
  db-password: {{ .Values.platform.postgres.credentials.password | quote }}
  database-url: {{ .Values.platform.api.env.DATABASE_URL | quote }}
